// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlWQ78GS9QZ4DkDRfCueOlAObdxVkXUG4',
    appId: '1:564253287329:web:77d711354d5ba3d92461e0',
    messagingSenderId: '564253287329',
    projectId: 'mjolo69',
    authDomain: 'mjolo69.firebaseapp.com',
    storageBucket: 'mjolo69.firebasestorage.app',
    measurementId: 'G-6MXG6G1GX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGBJaqfwjE7mpFceTDUNOEEhA6k6TLOtg',
    appId: '1:564253287329:android:a59fe273a06b03732461e0',
    messagingSenderId: '564253287329',
    projectId: 'mjolo69',
    storageBucket: 'mjolo69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBpIRJnYLx8ofZd9OmQoOODKxpR8zaPvo',
    appId: '1:564253287329:ios:66308b7f1b3b41a92461e0',
    messagingSenderId: '564253287329',
    projectId: 'mjolo69',
    storageBucket: 'mjolo69.firebasestorage.app',
    androidClientId: '564253287329-te8ed99sab8eo9poj8bp9rgaki3mf9gh.apps.googleusercontent.com',
    iosClientId: '564253287329-bb9484c98nn3bv65g32epj7bo0ihjlj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherForecastApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBpIRJnYLx8ofZd9OmQoOODKxpR8zaPvo',
    appId: '1:564253287329:ios:66308b7f1b3b41a92461e0',
    messagingSenderId: '564253287329',
    projectId: 'mjolo69',
    storageBucket: 'mjolo69.firebasestorage.app',
    androidClientId: '564253287329-te8ed99sab8eo9poj8bp9rgaki3mf9gh.apps.googleusercontent.com',
    iosClientId: '564253287329-bb9484c98nn3bv65g32epj7bo0ihjlj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherForecastApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlWQ78GS9QZ4DkDRfCueOlAObdxVkXUG4',
    appId: '1:564253287329:web:d537b39ee53afd702461e0',
    messagingSenderId: '564253287329',
    projectId: 'mjolo69',
    authDomain: 'mjolo69.firebaseapp.com',
    storageBucket: 'mjolo69.firebasestorage.app',
    measurementId: 'G-3DFJ3HBZGG',
  );
}
